name: yourchat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  # for using  Icons 
  cupertino_icons: ^1.0.5
  lottie: ^2.3.1
  # for integration firebase
  firebase_core: ^2.8.0
  animated_text_kit: ^4.2.2
  # for handling Google sign in
  google_sign_in: ^6.0.2
  # for handling firebase authentication
  firebase_auth: ^4.4.0
  # for accessing cloud firebase database
  cloud_firestore: ^4.5.0
  #for showing network image
  cached_network_image: ^3.2.3
  #image picker to gallery and camera
  image_picker: ^0.8.7+1
  #fire storage access(for uploading file)
  firebase_storage: ^11.1.0
  #emoji picker
  emoji_picker_flutter: ^1.5.2
  #for accessing firebase messaging (push notification)
  firebase_messaging: ^14.4.0
  #save image to gallery 
  gallery_saver: ^2.3.2
  

 
dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: ^0.12.0
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/icon.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true
  
 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - icon/
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
